# The following is an example of a Deployment. 
# It creates a ReplicaSet to bring up three nginx Pods:
# Deployment -> ReplicaSet -> Pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2

        volumeMounts:
        - name: db-connection
          mountPath: /opt/db-connection 
        # Instead of using env to get value from ConfigMap we can use volumes
        # env:  
        # - name: DB-PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: test-cm
        #       key: db-port
        ports:
        - containerPort: 80
      volumes:
      - name: db-connection
        configMap:
          name: test-cm
          items:
          - key: db-port
            path: db-port